/*
CodeSandbox API

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codesandboxsdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/callstackai/codesandboxsdk"
)

func Test_codesandboxsdk_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService TokenCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var teamId string

		resp, httpRes, err := apiClient.DefaultAPI.TokenCreate(context.Background(), teamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService TokenUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var teamId string
		var tokenId string

		resp, httpRes, err := apiClient.DefaultAPI.TokenUpdate(context.Background(), teamId, tokenId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService WorkspaceCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.WorkspaceCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
