/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
)

// checks if the SandboxForkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxForkResponse{}

// SandboxForkResponse struct for SandboxForkResponse
type SandboxForkResponse struct {
	Errors []Error3 `json:"errors,omitempty"`
	Success *bool `json:"success,omitempty"`
	Data *SandboxForkResponseAllOfData `json:"data,omitempty"`
}

// NewSandboxForkResponse instantiates a new SandboxForkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxForkResponse() *SandboxForkResponse {
	this := SandboxForkResponse{}
	return &this
}

// NewSandboxForkResponseWithDefaults instantiates a new SandboxForkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxForkResponseWithDefaults() *SandboxForkResponse {
	this := SandboxForkResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *SandboxForkResponse) GetErrors() []Error3 {
	if o == nil || IsNil(o.Errors) {
		var ret []Error3
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxForkResponse) GetErrorsOk() ([]Error3, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *SandboxForkResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error3 and assigns it to the Errors field.
func (o *SandboxForkResponse) SetErrors(v []Error3) {
	o.Errors = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *SandboxForkResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxForkResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *SandboxForkResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *SandboxForkResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SandboxForkResponse) GetData() SandboxForkResponseAllOfData {
	if o == nil || IsNil(o.Data) {
		var ret SandboxForkResponseAllOfData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxForkResponse) GetDataOk() (*SandboxForkResponseAllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SandboxForkResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SandboxForkResponseAllOfData and assigns it to the Data field.
func (o *SandboxForkResponse) SetData(v SandboxForkResponseAllOfData) {
	o.Data = &v
}

func (o SandboxForkResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxForkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSandboxForkResponse struct {
	value *SandboxForkResponse
	isSet bool
}

func (v NullableSandboxForkResponse) Get() *SandboxForkResponse {
	return v.value
}

func (v *NullableSandboxForkResponse) Set(val *SandboxForkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxForkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxForkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxForkResponse(val *SandboxForkResponse) *NullableSandboxForkResponse {
	return &NullableSandboxForkResponse{value: val, isSet: true}
}

func (v NullableSandboxForkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxForkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


