/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkspaceCreateResponseAllOfData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceCreateResponseAllOfData{}

// WorkspaceCreateResponseAllOfData struct for WorkspaceCreateResponseAllOfData
type WorkspaceCreateResponseAllOfData struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type _WorkspaceCreateResponseAllOfData WorkspaceCreateResponseAllOfData

// NewWorkspaceCreateResponseAllOfData instantiates a new WorkspaceCreateResponseAllOfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceCreateResponseAllOfData(id string, name string) *WorkspaceCreateResponseAllOfData {
	this := WorkspaceCreateResponseAllOfData{}
	this.Id = id
	this.Name = name
	return &this
}

// NewWorkspaceCreateResponseAllOfDataWithDefaults instantiates a new WorkspaceCreateResponseAllOfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceCreateResponseAllOfDataWithDefaults() *WorkspaceCreateResponseAllOfData {
	this := WorkspaceCreateResponseAllOfData{}
	return &this
}

// GetId returns the Id field value
func (o *WorkspaceCreateResponseAllOfData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkspaceCreateResponseAllOfData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkspaceCreateResponseAllOfData) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *WorkspaceCreateResponseAllOfData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkspaceCreateResponseAllOfData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkspaceCreateResponseAllOfData) SetName(v string) {
	o.Name = v
}

func (o WorkspaceCreateResponseAllOfData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceCreateResponseAllOfData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *WorkspaceCreateResponseAllOfData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspaceCreateResponseAllOfData := _WorkspaceCreateResponseAllOfData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspaceCreateResponseAllOfData)

	if err != nil {
		return err
	}

	*o = WorkspaceCreateResponseAllOfData(varWorkspaceCreateResponseAllOfData)

	return err
}

type NullableWorkspaceCreateResponseAllOfData struct {
	value *WorkspaceCreateResponseAllOfData
	isSet bool
}

func (v NullableWorkspaceCreateResponseAllOfData) Get() *WorkspaceCreateResponseAllOfData {
	return v.value
}

func (v *NullableWorkspaceCreateResponseAllOfData) Set(val *WorkspaceCreateResponseAllOfData) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceCreateResponseAllOfData) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceCreateResponseAllOfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceCreateResponseAllOfData(val *WorkspaceCreateResponseAllOfData) *NullableWorkspaceCreateResponseAllOfData {
	return &NullableWorkspaceCreateResponseAllOfData{value: val, isSet: true}
}

func (v NullableWorkspaceCreateResponseAllOfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceCreateResponseAllOfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


