/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VMUpdateHibernationTimeoutResponseAllOfData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VMUpdateHibernationTimeoutResponseAllOfData{}

// VMUpdateHibernationTimeoutResponseAllOfData struct for VMUpdateHibernationTimeoutResponseAllOfData
type VMUpdateHibernationTimeoutResponseAllOfData struct {
	HibernationTimeoutSeconds int32 `json:"hibernation_timeout_seconds"`
	Id string `json:"id"`
}

type _VMUpdateHibernationTimeoutResponseAllOfData VMUpdateHibernationTimeoutResponseAllOfData

// NewVMUpdateHibernationTimeoutResponseAllOfData instantiates a new VMUpdateHibernationTimeoutResponseAllOfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVMUpdateHibernationTimeoutResponseAllOfData(hibernationTimeoutSeconds int32, id string) *VMUpdateHibernationTimeoutResponseAllOfData {
	this := VMUpdateHibernationTimeoutResponseAllOfData{}
	this.HibernationTimeoutSeconds = hibernationTimeoutSeconds
	this.Id = id
	return &this
}

// NewVMUpdateHibernationTimeoutResponseAllOfDataWithDefaults instantiates a new VMUpdateHibernationTimeoutResponseAllOfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVMUpdateHibernationTimeoutResponseAllOfDataWithDefaults() *VMUpdateHibernationTimeoutResponseAllOfData {
	this := VMUpdateHibernationTimeoutResponseAllOfData{}
	return &this
}

// GetHibernationTimeoutSeconds returns the HibernationTimeoutSeconds field value
func (o *VMUpdateHibernationTimeoutResponseAllOfData) GetHibernationTimeoutSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HibernationTimeoutSeconds
}

// GetHibernationTimeoutSecondsOk returns a tuple with the HibernationTimeoutSeconds field value
// and a boolean to check if the value has been set.
func (o *VMUpdateHibernationTimeoutResponseAllOfData) GetHibernationTimeoutSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HibernationTimeoutSeconds, true
}

// SetHibernationTimeoutSeconds sets field value
func (o *VMUpdateHibernationTimeoutResponseAllOfData) SetHibernationTimeoutSeconds(v int32) {
	o.HibernationTimeoutSeconds = v
}

// GetId returns the Id field value
func (o *VMUpdateHibernationTimeoutResponseAllOfData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VMUpdateHibernationTimeoutResponseAllOfData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VMUpdateHibernationTimeoutResponseAllOfData) SetId(v string) {
	o.Id = v
}

func (o VMUpdateHibernationTimeoutResponseAllOfData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VMUpdateHibernationTimeoutResponseAllOfData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hibernation_timeout_seconds"] = o.HibernationTimeoutSeconds
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *VMUpdateHibernationTimeoutResponseAllOfData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hibernation_timeout_seconds",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVMUpdateHibernationTimeoutResponseAllOfData := _VMUpdateHibernationTimeoutResponseAllOfData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVMUpdateHibernationTimeoutResponseAllOfData)

	if err != nil {
		return err
	}

	*o = VMUpdateHibernationTimeoutResponseAllOfData(varVMUpdateHibernationTimeoutResponseAllOfData)

	return err
}

type NullableVMUpdateHibernationTimeoutResponseAllOfData struct {
	value *VMUpdateHibernationTimeoutResponseAllOfData
	isSet bool
}

func (v NullableVMUpdateHibernationTimeoutResponseAllOfData) Get() *VMUpdateHibernationTimeoutResponseAllOfData {
	return v.value
}

func (v *NullableVMUpdateHibernationTimeoutResponseAllOfData) Set(val *VMUpdateHibernationTimeoutResponseAllOfData) {
	v.value = val
	v.isSet = true
}

func (v NullableVMUpdateHibernationTimeoutResponseAllOfData) IsSet() bool {
	return v.isSet
}

func (v *NullableVMUpdateHibernationTimeoutResponseAllOfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVMUpdateHibernationTimeoutResponseAllOfData(val *VMUpdateHibernationTimeoutResponseAllOfData) *NullableVMUpdateHibernationTimeoutResponseAllOfData {
	return &NullableVMUpdateHibernationTimeoutResponseAllOfData{value: val, isSet: true}
}

func (v NullableVMUpdateHibernationTimeoutResponseAllOfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVMUpdateHibernationTimeoutResponseAllOfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


