/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MetaInformationApi type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaInformationApi{}

// MetaInformationApi Meta information about the CodeSandbox API
type MetaInformationApi struct {
	LatestVersion string `json:"latest_version"`
	Name string `json:"name"`
}

type _MetaInformationApi MetaInformationApi

// NewMetaInformationApi instantiates a new MetaInformationApi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaInformationApi(latestVersion string, name string) *MetaInformationApi {
	this := MetaInformationApi{}
	this.LatestVersion = latestVersion
	this.Name = name
	return &this
}

// NewMetaInformationApiWithDefaults instantiates a new MetaInformationApi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaInformationApiWithDefaults() *MetaInformationApi {
	this := MetaInformationApi{}
	return &this
}

// GetLatestVersion returns the LatestVersion field value
func (o *MetaInformationApi) GetLatestVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LatestVersion
}

// GetLatestVersionOk returns a tuple with the LatestVersion field value
// and a boolean to check if the value has been set.
func (o *MetaInformationApi) GetLatestVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestVersion, true
}

// SetLatestVersion sets field value
func (o *MetaInformationApi) SetLatestVersion(v string) {
	o.LatestVersion = v
}

// GetName returns the Name field value
func (o *MetaInformationApi) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MetaInformationApi) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MetaInformationApi) SetName(v string) {
	o.Name = v
}

func (o MetaInformationApi) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaInformationApi) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["latest_version"] = o.LatestVersion
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *MetaInformationApi) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"latest_version",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetaInformationApi := _MetaInformationApi{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetaInformationApi)

	if err != nil {
		return err
	}

	*o = MetaInformationApi(varMetaInformationApi)

	return err
}

type NullableMetaInformationApi struct {
	value *MetaInformationApi
	isSet bool
}

func (v NullableMetaInformationApi) Get() *MetaInformationApi {
	return v.value
}

func (v *NullableMetaInformationApi) Set(val *MetaInformationApi) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaInformationApi) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaInformationApi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaInformationApi(val *MetaInformationApi) *NullableMetaInformationApi {
	return &NullableMetaInformationApi{value: val, isSet: true}
}

func (v NullableMetaInformationApi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaInformationApi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


