/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// Error10 - struct for Error10
type Error10 struct {
	MapmapOfStringAny *map[string]interface{}
	String *string
}

// map[string]interface{}AsError10 is a convenience function that returns map[string]interface{} wrapped in Error10
func MapmapOfStringAnyAsError10(v *map[string]interface{}) Error10 {
	return Error10{
		MapmapOfStringAny: v,
	}
}

// stringAsError10 is a convenience function that returns string wrapped in Error10
func StringAsError10(v *string) Error10 {
	return Error10{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Error10) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MapmapOfStringAny = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Error10)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Error10)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Error10) MarshalJSON() ([]byte, error) {
	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Error10) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableError10 struct {
	value *Error10
	isSet bool
}

func (v NullableError10) Get() *Error10 {
	return v.value
}

func (v *NullableError10) Set(val *Error10) {
	v.value = val
	v.isSet = true
}

func (v NullableError10) IsSet() bool {
	return v.isSet
}

func (v *NullableError10) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableError10(val *Error10) *NullableError10 {
	return &NullableError10{value: val, isSet: true}
}

func (v NullableError10) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableError10) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


