/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SandboxListResponseAllOfData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxListResponseAllOfData{}

// SandboxListResponseAllOfData struct for SandboxListResponseAllOfData
type SandboxListResponseAllOfData struct {
	Sandboxes []SandboxGetResponseAllOfData `json:"sandboxes"`
}

type _SandboxListResponseAllOfData SandboxListResponseAllOfData

// NewSandboxListResponseAllOfData instantiates a new SandboxListResponseAllOfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxListResponseAllOfData(sandboxes []SandboxGetResponseAllOfData) *SandboxListResponseAllOfData {
	this := SandboxListResponseAllOfData{}
	this.Sandboxes = sandboxes
	return &this
}

// NewSandboxListResponseAllOfDataWithDefaults instantiates a new SandboxListResponseAllOfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxListResponseAllOfDataWithDefaults() *SandboxListResponseAllOfData {
	this := SandboxListResponseAllOfData{}
	return &this
}

// GetSandboxes returns the Sandboxes field value
func (o *SandboxListResponseAllOfData) GetSandboxes() []SandboxGetResponseAllOfData {
	if o == nil {
		var ret []SandboxGetResponseAllOfData
		return ret
	}

	return o.Sandboxes
}

// GetSandboxesOk returns a tuple with the Sandboxes field value
// and a boolean to check if the value has been set.
func (o *SandboxListResponseAllOfData) GetSandboxesOk() ([]SandboxGetResponseAllOfData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sandboxes, true
}

// SetSandboxes sets field value
func (o *SandboxListResponseAllOfData) SetSandboxes(v []SandboxGetResponseAllOfData) {
	o.Sandboxes = v
}

func (o SandboxListResponseAllOfData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxListResponseAllOfData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sandboxes"] = o.Sandboxes
	return toSerialize, nil
}

func (o *SandboxListResponseAllOfData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sandboxes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSandboxListResponseAllOfData := _SandboxListResponseAllOfData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSandboxListResponseAllOfData)

	if err != nil {
		return err
	}

	*o = SandboxListResponseAllOfData(varSandboxListResponseAllOfData)

	return err
}

type NullableSandboxListResponseAllOfData struct {
	value *SandboxListResponseAllOfData
	isSet bool
}

func (v NullableSandboxListResponseAllOfData) Get() *SandboxListResponseAllOfData {
	return v.value
}

func (v *NullableSandboxListResponseAllOfData) Set(val *SandboxListResponseAllOfData) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxListResponseAllOfData) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxListResponseAllOfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxListResponseAllOfData(val *SandboxListResponseAllOfData) *NullableSandboxListResponseAllOfData {
	return &NullableSandboxListResponseAllOfData{value: val, isSet: true}
}

func (v NullableSandboxListResponseAllOfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxListResponseAllOfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


