/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
	"time"
)

// checks if the TokenCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenCreateRequest{}

// TokenCreateRequest struct for TokenCreateRequest
type TokenCreateRequest struct {
	// API Version to use, formatted as YYYY-MM-DD. Defaults to the latest version at time of creation.
	DefaultVersion NullableString `json:"default_version,omitempty"`
	// Description of this token, for instance where it will be used.
	Description *string `json:"description,omitempty"`
	// UTC Timestamp until when this token is valid. Omitting this field will create a token without an expiry.
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
	// Which scopes to grant this token. The given scopes will replace the current scopes, revoking any that are no longer present in the list.
	Scopes []string `json:"scopes,omitempty"`
}

// NewTokenCreateRequest instantiates a new TokenCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenCreateRequest() *TokenCreateRequest {
	this := TokenCreateRequest{}
	return &this
}

// NewTokenCreateRequestWithDefaults instantiates a new TokenCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenCreateRequestWithDefaults() *TokenCreateRequest {
	this := TokenCreateRequest{}
	return &this
}

// GetDefaultVersion returns the DefaultVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenCreateRequest) GetDefaultVersion() string {
	if o == nil || IsNil(o.DefaultVersion.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultVersion.Get()
}

// GetDefaultVersionOk returns a tuple with the DefaultVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenCreateRequest) GetDefaultVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultVersion.Get(), o.DefaultVersion.IsSet()
}

// HasDefaultVersion returns a boolean if a field has been set.
func (o *TokenCreateRequest) HasDefaultVersion() bool {
	if o != nil && o.DefaultVersion.IsSet() {
		return true
	}

	return false
}

// SetDefaultVersion gets a reference to the given NullableString and assigns it to the DefaultVersion field.
func (o *TokenCreateRequest) SetDefaultVersion(v string) {
	o.DefaultVersion.Set(&v)
}
// SetDefaultVersionNil sets the value for DefaultVersion to be an explicit nil
func (o *TokenCreateRequest) SetDefaultVersionNil() {
	o.DefaultVersion.Set(nil)
}

// UnsetDefaultVersion ensures that no value is present for DefaultVersion, not even an explicit nil
func (o *TokenCreateRequest) UnsetDefaultVersion() {
	o.DefaultVersion.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TokenCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TokenCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TokenCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenCreateRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenCreateRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *TokenCreateRequest) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *TokenCreateRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *TokenCreateRequest) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *TokenCreateRequest) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *TokenCreateRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenCreateRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *TokenCreateRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *TokenCreateRequest) SetScopes(v []string) {
	o.Scopes = v
}

func (o TokenCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultVersion.IsSet() {
		toSerialize["default_version"] = o.DefaultVersion.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	return toSerialize, nil
}

type NullableTokenCreateRequest struct {
	value *TokenCreateRequest
	isSet bool
}

func (v NullableTokenCreateRequest) Get() *TokenCreateRequest {
	return v.value
}

func (v *NullableTokenCreateRequest) Set(val *TokenCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenCreateRequest(val *TokenCreateRequest) *NullableTokenCreateRequest {
	return &NullableTokenCreateRequest{value: val, isSet: true}
}

func (v NullableTokenCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


