/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
)

// checks if the VMShutdownResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VMShutdownResponse{}

// VMShutdownResponse struct for VMShutdownResponse
type VMShutdownResponse struct {
	Errors []Error9 `json:"errors,omitempty"`
	Success *bool `json:"success,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewVMShutdownResponse instantiates a new VMShutdownResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVMShutdownResponse() *VMShutdownResponse {
	this := VMShutdownResponse{}
	return &this
}

// NewVMShutdownResponseWithDefaults instantiates a new VMShutdownResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVMShutdownResponseWithDefaults() *VMShutdownResponse {
	this := VMShutdownResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *VMShutdownResponse) GetErrors() []Error9 {
	if o == nil || IsNil(o.Errors) {
		var ret []Error9
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMShutdownResponse) GetErrorsOk() ([]Error9, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *VMShutdownResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error9 and assigns it to the Errors field.
func (o *VMShutdownResponse) SetErrors(v []Error9) {
	o.Errors = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *VMShutdownResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMShutdownResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *VMShutdownResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *VMShutdownResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *VMShutdownResponse) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMShutdownResponse) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *VMShutdownResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *VMShutdownResponse) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o VMShutdownResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VMShutdownResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableVMShutdownResponse struct {
	value *VMShutdownResponse
	isSet bool
}

func (v NullableVMShutdownResponse) Get() *VMShutdownResponse {
	return v.value
}

func (v *NullableVMShutdownResponse) Set(val *VMShutdownResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVMShutdownResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVMShutdownResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVMShutdownResponse(val *VMShutdownResponse) *NullableVMShutdownResponse {
	return &NullableVMShutdownResponse{value: val, isSet: true}
}

func (v NullableVMShutdownResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVMShutdownResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


