/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
)

// checks if the VMUpdateHibernationTimeoutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VMUpdateHibernationTimeoutResponse{}

// VMUpdateHibernationTimeoutResponse struct for VMUpdateHibernationTimeoutResponse
type VMUpdateHibernationTimeoutResponse struct {
	Errors []Error11 `json:"errors,omitempty"`
	Success *bool `json:"success,omitempty"`
	Data *VMUpdateHibernationTimeoutResponseAllOfData `json:"data,omitempty"`
}

// NewVMUpdateHibernationTimeoutResponse instantiates a new VMUpdateHibernationTimeoutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVMUpdateHibernationTimeoutResponse() *VMUpdateHibernationTimeoutResponse {
	this := VMUpdateHibernationTimeoutResponse{}
	return &this
}

// NewVMUpdateHibernationTimeoutResponseWithDefaults instantiates a new VMUpdateHibernationTimeoutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVMUpdateHibernationTimeoutResponseWithDefaults() *VMUpdateHibernationTimeoutResponse {
	this := VMUpdateHibernationTimeoutResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *VMUpdateHibernationTimeoutResponse) GetErrors() []Error11 {
	if o == nil || IsNil(o.Errors) {
		var ret []Error11
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMUpdateHibernationTimeoutResponse) GetErrorsOk() ([]Error11, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *VMUpdateHibernationTimeoutResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error11 and assigns it to the Errors field.
func (o *VMUpdateHibernationTimeoutResponse) SetErrors(v []Error11) {
	o.Errors = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *VMUpdateHibernationTimeoutResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMUpdateHibernationTimeoutResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *VMUpdateHibernationTimeoutResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *VMUpdateHibernationTimeoutResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *VMUpdateHibernationTimeoutResponse) GetData() VMUpdateHibernationTimeoutResponseAllOfData {
	if o == nil || IsNil(o.Data) {
		var ret VMUpdateHibernationTimeoutResponseAllOfData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMUpdateHibernationTimeoutResponse) GetDataOk() (*VMUpdateHibernationTimeoutResponseAllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *VMUpdateHibernationTimeoutResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given VMUpdateHibernationTimeoutResponseAllOfData and assigns it to the Data field.
func (o *VMUpdateHibernationTimeoutResponse) SetData(v VMUpdateHibernationTimeoutResponseAllOfData) {
	o.Data = &v
}

func (o VMUpdateHibernationTimeoutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VMUpdateHibernationTimeoutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableVMUpdateHibernationTimeoutResponse struct {
	value *VMUpdateHibernationTimeoutResponse
	isSet bool
}

func (v NullableVMUpdateHibernationTimeoutResponse) Get() *VMUpdateHibernationTimeoutResponse {
	return v.value
}

func (v *NullableVMUpdateHibernationTimeoutResponse) Set(val *VMUpdateHibernationTimeoutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVMUpdateHibernationTimeoutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVMUpdateHibernationTimeoutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVMUpdateHibernationTimeoutResponse(val *VMUpdateHibernationTimeoutResponse) *NullableVMUpdateHibernationTimeoutResponse {
	return &NullableVMUpdateHibernationTimeoutResponse{value: val, isSet: true}
}

func (v NullableVMUpdateHibernationTimeoutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVMUpdateHibernationTimeoutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


