/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SandboxCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxCreateRequest{}

// SandboxCreateRequest struct for SandboxCreateRequest
type SandboxCreateRequest struct {
	// Optional text description of the sandbox. Defaults to no description.
	Description *string `json:"description,omitempty"`
	// Filename of the entrypoint of the sandbox.
	Entry *string `json:"entry,omitempty"`
	// Array of strings with external resources to load.
	ExternalResources []string `json:"external_resources,omitempty"`
	// Map of `path => file` where each file is a map.
	Files map[string]SandboxCreateRequestFilesValue `json:"files"`
	// Whether changes to the sandbox are disallowed. Defaults to `false`.
	IsFrozen *bool `json:"is_frozen,omitempty"`
	// Map of dependencies and their version specifications.
	NpmDependencies *map[string]string `json:"npm_dependencies,omitempty"`
	// Path to the collection where the new sandbox should be stored. Defaults to \"/\". If no collection exists at the given path, it will be created.
	Path *string `json:"path,omitempty"`
	// 0 for public, 1 for unlisted, and 2 for private. Privacy is subject to certain restrictions (team minimum setting, drafts must be private, etc.). Defaults to public.
	Privacy *int32 `json:"privacy,omitempty"`
	// Runtime to use for the sandbox. Defaults to `\"browser\"`.
	Runtime *string `json:"runtime,omitempty"`
	// List of string tags to apply to the sandbox. Only the first ten will be used. Defaults to no tags.
	Tags []string `json:"tags,omitempty"`
	// Name of the template from which the sandbox is derived (for example, `\"static\"`).
	Template *string `json:"template,omitempty"`
	// Sandbox title. Maximum 255 characters. Defaults to no title.
	Title *string `json:"title,omitempty"`
}

type _SandboxCreateRequest SandboxCreateRequest

// NewSandboxCreateRequest instantiates a new SandboxCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxCreateRequest(files map[string]SandboxCreateRequestFilesValue) *SandboxCreateRequest {
	this := SandboxCreateRequest{}
	this.Files = files
	var isFrozen bool = false
	this.IsFrozen = &isFrozen
	var path string = "/"
	this.Path = &path
	var privacy int32 = 0
	this.Privacy = &privacy
	var runtime string = "browser"
	this.Runtime = &runtime
	var title string = ""
	this.Title = &title
	return &this
}

// NewSandboxCreateRequestWithDefaults instantiates a new SandboxCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxCreateRequestWithDefaults() *SandboxCreateRequest {
	this := SandboxCreateRequest{}
	var isFrozen bool = false
	this.IsFrozen = &isFrozen
	var path string = "/"
	this.Path = &path
	var privacy int32 = 0
	this.Privacy = &privacy
	var runtime string = "browser"
	this.Runtime = &runtime
	var title string = ""
	this.Title = &title
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SandboxCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEntry returns the Entry field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetEntry() string {
	if o == nil || IsNil(o.Entry) {
		var ret string
		return ret
	}
	return *o.Entry
}

// GetEntryOk returns a tuple with the Entry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetEntryOk() (*string, bool) {
	if o == nil || IsNil(o.Entry) {
		return nil, false
	}
	return o.Entry, true
}

// HasEntry returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasEntry() bool {
	if o != nil && !IsNil(o.Entry) {
		return true
	}

	return false
}

// SetEntry gets a reference to the given string and assigns it to the Entry field.
func (o *SandboxCreateRequest) SetEntry(v string) {
	o.Entry = &v
}

// GetExternalResources returns the ExternalResources field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetExternalResources() []string {
	if o == nil || IsNil(o.ExternalResources) {
		var ret []string
		return ret
	}
	return o.ExternalResources
}

// GetExternalResourcesOk returns a tuple with the ExternalResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetExternalResourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.ExternalResources) {
		return nil, false
	}
	return o.ExternalResources, true
}

// HasExternalResources returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasExternalResources() bool {
	if o != nil && !IsNil(o.ExternalResources) {
		return true
	}

	return false
}

// SetExternalResources gets a reference to the given []string and assigns it to the ExternalResources field.
func (o *SandboxCreateRequest) SetExternalResources(v []string) {
	o.ExternalResources = v
}

// GetFiles returns the Files field value
func (o *SandboxCreateRequest) GetFiles() map[string]SandboxCreateRequestFilesValue {
	if o == nil {
		var ret map[string]SandboxCreateRequestFilesValue
		return ret
	}

	return o.Files
}

// GetFilesOk returns a tuple with the Files field value
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetFilesOk() (*map[string]SandboxCreateRequestFilesValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Files, true
}

// SetFiles sets field value
func (o *SandboxCreateRequest) SetFiles(v map[string]SandboxCreateRequestFilesValue) {
	o.Files = v
}

// GetIsFrozen returns the IsFrozen field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetIsFrozen() bool {
	if o == nil || IsNil(o.IsFrozen) {
		var ret bool
		return ret
	}
	return *o.IsFrozen
}

// GetIsFrozenOk returns a tuple with the IsFrozen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetIsFrozenOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFrozen) {
		return nil, false
	}
	return o.IsFrozen, true
}

// HasIsFrozen returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasIsFrozen() bool {
	if o != nil && !IsNil(o.IsFrozen) {
		return true
	}

	return false
}

// SetIsFrozen gets a reference to the given bool and assigns it to the IsFrozen field.
func (o *SandboxCreateRequest) SetIsFrozen(v bool) {
	o.IsFrozen = &v
}

// GetNpmDependencies returns the NpmDependencies field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetNpmDependencies() map[string]string {
	if o == nil || IsNil(o.NpmDependencies) {
		var ret map[string]string
		return ret
	}
	return *o.NpmDependencies
}

// GetNpmDependenciesOk returns a tuple with the NpmDependencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetNpmDependenciesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.NpmDependencies) {
		return nil, false
	}
	return o.NpmDependencies, true
}

// HasNpmDependencies returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasNpmDependencies() bool {
	if o != nil && !IsNil(o.NpmDependencies) {
		return true
	}

	return false
}

// SetNpmDependencies gets a reference to the given map[string]string and assigns it to the NpmDependencies field.
func (o *SandboxCreateRequest) SetNpmDependencies(v map[string]string) {
	o.NpmDependencies = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *SandboxCreateRequest) SetPath(v string) {
	o.Path = &v
}

// GetPrivacy returns the Privacy field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetPrivacy() int32 {
	if o == nil || IsNil(o.Privacy) {
		var ret int32
		return ret
	}
	return *o.Privacy
}

// GetPrivacyOk returns a tuple with the Privacy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetPrivacyOk() (*int32, bool) {
	if o == nil || IsNil(o.Privacy) {
		return nil, false
	}
	return o.Privacy, true
}

// HasPrivacy returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasPrivacy() bool {
	if o != nil && !IsNil(o.Privacy) {
		return true
	}

	return false
}

// SetPrivacy gets a reference to the given int32 and assigns it to the Privacy field.
func (o *SandboxCreateRequest) SetPrivacy(v int32) {
	o.Privacy = &v
}

// GetRuntime returns the Runtime field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetRuntime() string {
	if o == nil || IsNil(o.Runtime) {
		var ret string
		return ret
	}
	return *o.Runtime
}

// GetRuntimeOk returns a tuple with the Runtime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetRuntimeOk() (*string, bool) {
	if o == nil || IsNil(o.Runtime) {
		return nil, false
	}
	return o.Runtime, true
}

// HasRuntime returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasRuntime() bool {
	if o != nil && !IsNil(o.Runtime) {
		return true
	}

	return false
}

// SetRuntime gets a reference to the given string and assigns it to the Runtime field.
func (o *SandboxCreateRequest) SetRuntime(v string) {
	o.Runtime = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SandboxCreateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetTemplate() string {
	if o == nil || IsNil(o.Template) {
		var ret string
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given string and assigns it to the Template field.
func (o *SandboxCreateRequest) SetTemplate(v string) {
	o.Template = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *SandboxCreateRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxCreateRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *SandboxCreateRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *SandboxCreateRequest) SetTitle(v string) {
	o.Title = &v
}

func (o SandboxCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Entry) {
		toSerialize["entry"] = o.Entry
	}
	if !IsNil(o.ExternalResources) {
		toSerialize["external_resources"] = o.ExternalResources
	}
	toSerialize["files"] = o.Files
	if !IsNil(o.IsFrozen) {
		toSerialize["is_frozen"] = o.IsFrozen
	}
	if !IsNil(o.NpmDependencies) {
		toSerialize["npm_dependencies"] = o.NpmDependencies
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Privacy) {
		toSerialize["privacy"] = o.Privacy
	}
	if !IsNil(o.Runtime) {
		toSerialize["runtime"] = o.Runtime
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

func (o *SandboxCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"files",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSandboxCreateRequest := _SandboxCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSandboxCreateRequest)

	if err != nil {
		return err
	}

	*o = SandboxCreateRequest(varSandboxCreateRequest)

	return err
}

type NullableSandboxCreateRequest struct {
	value *SandboxCreateRequest
	isSet bool
}

func (v NullableSandboxCreateRequest) Get() *SandboxCreateRequest {
	return v.value
}

func (v *NullableSandboxCreateRequest) Set(val *SandboxCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxCreateRequest(val *SandboxCreateRequest) *NullableSandboxCreateRequest {
	return &NullableSandboxCreateRequest{value: val, isSet: true}
}

func (v NullableSandboxCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


