/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
)

// checks if the VMUpdateSpecsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VMUpdateSpecsResponse{}

// VMUpdateSpecsResponse struct for VMUpdateSpecsResponse
type VMUpdateSpecsResponse struct {
	Errors []Error12 `json:"errors,omitempty"`
	Success *bool `json:"success,omitempty"`
	Data *VMUpdateSpecsResponseAllOfData `json:"data,omitempty"`
}

// NewVMUpdateSpecsResponse instantiates a new VMUpdateSpecsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVMUpdateSpecsResponse() *VMUpdateSpecsResponse {
	this := VMUpdateSpecsResponse{}
	return &this
}

// NewVMUpdateSpecsResponseWithDefaults instantiates a new VMUpdateSpecsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVMUpdateSpecsResponseWithDefaults() *VMUpdateSpecsResponse {
	this := VMUpdateSpecsResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *VMUpdateSpecsResponse) GetErrors() []Error12 {
	if o == nil || IsNil(o.Errors) {
		var ret []Error12
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMUpdateSpecsResponse) GetErrorsOk() ([]Error12, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *VMUpdateSpecsResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error12 and assigns it to the Errors field.
func (o *VMUpdateSpecsResponse) SetErrors(v []Error12) {
	o.Errors = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *VMUpdateSpecsResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMUpdateSpecsResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *VMUpdateSpecsResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *VMUpdateSpecsResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *VMUpdateSpecsResponse) GetData() VMUpdateSpecsResponseAllOfData {
	if o == nil || IsNil(o.Data) {
		var ret VMUpdateSpecsResponseAllOfData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMUpdateSpecsResponse) GetDataOk() (*VMUpdateSpecsResponseAllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *VMUpdateSpecsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given VMUpdateSpecsResponseAllOfData and assigns it to the Data field.
func (o *VMUpdateSpecsResponse) SetData(v VMUpdateSpecsResponseAllOfData) {
	o.Data = &v
}

func (o VMUpdateSpecsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VMUpdateSpecsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableVMUpdateSpecsResponse struct {
	value *VMUpdateSpecsResponse
	isSet bool
}

func (v NullableVMUpdateSpecsResponse) Get() *VMUpdateSpecsResponse {
	return v.value
}

func (v *NullableVMUpdateSpecsResponse) Set(val *VMUpdateSpecsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVMUpdateSpecsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVMUpdateSpecsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVMUpdateSpecsResponse(val *VMUpdateSpecsResponse) *NullableVMUpdateSpecsResponse {
	return &NullableVMUpdateSpecsResponse{value: val, isSet: true}
}

func (v NullableVMUpdateSpecsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVMUpdateSpecsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


