/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
)

// checks if the SandboxGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxGetResponse{}

// SandboxGetResponse struct for SandboxGetResponse
type SandboxGetResponse struct {
	Errors []Error4 `json:"errors,omitempty"`
	Success *bool `json:"success,omitempty"`
	Data *SandboxGetResponseAllOfData `json:"data,omitempty"`
}

// NewSandboxGetResponse instantiates a new SandboxGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxGetResponse() *SandboxGetResponse {
	this := SandboxGetResponse{}
	return &this
}

// NewSandboxGetResponseWithDefaults instantiates a new SandboxGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxGetResponseWithDefaults() *SandboxGetResponse {
	this := SandboxGetResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *SandboxGetResponse) GetErrors() []Error4 {
	if o == nil || IsNil(o.Errors) {
		var ret []Error4
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxGetResponse) GetErrorsOk() ([]Error4, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *SandboxGetResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error4 and assigns it to the Errors field.
func (o *SandboxGetResponse) SetErrors(v []Error4) {
	o.Errors = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *SandboxGetResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxGetResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *SandboxGetResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *SandboxGetResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SandboxGetResponse) GetData() SandboxGetResponseAllOfData {
	if o == nil || IsNil(o.Data) {
		var ret SandboxGetResponseAllOfData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxGetResponse) GetDataOk() (*SandboxGetResponseAllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SandboxGetResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SandboxGetResponseAllOfData and assigns it to the Data field.
func (o *SandboxGetResponse) SetData(v SandboxGetResponseAllOfData) {
	o.Data = &v
}

func (o SandboxGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSandboxGetResponse struct {
	value *SandboxGetResponse
	isSet bool
}

func (v NullableSandboxGetResponse) Get() *SandboxGetResponse {
	return v.value
}

func (v *NullableSandboxGetResponse) Set(val *SandboxGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxGetResponse(val *SandboxGetResponse) *NullableSandboxGetResponse {
	return &NullableSandboxGetResponse{value: val, isSet: true}
}

func (v NullableSandboxGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


