/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// Error8 - struct for Error8
type Error8 struct {
	MapmapOfStringAny *map[string]interface{}
	String *string
}

// map[string]interface{}AsError8 is a convenience function that returns map[string]interface{} wrapped in Error8
func MapmapOfStringAnyAsError8(v *map[string]interface{}) Error8 {
	return Error8{
		MapmapOfStringAny: v,
	}
}

// stringAsError8 is a convenience function that returns string wrapped in Error8
func StringAsError8(v *string) Error8 {
	return Error8{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Error8) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MapmapOfStringAny = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Error8)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Error8)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Error8) MarshalJSON() ([]byte, error) {
	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Error8) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableError8 struct {
	value *Error8
	isSet bool
}

func (v NullableError8) Get() *Error8 {
	return v.value
}

func (v *NullableError8) Set(val *Error8) {
	v.value = val
	v.isSet = true
}

func (v NullableError8) IsSet() bool {
	return v.isSet
}

func (v *NullableError8) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableError8(val *Error8) *NullableError8 {
	return &NullableError8{value: val, isSet: true}
}

func (v NullableError8) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableError8) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


