/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
)

// checks if the WorkspaceCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceCreateResponse{}

// WorkspaceCreateResponse struct for WorkspaceCreateResponse
type WorkspaceCreateResponse struct {
	Errors []Error13 `json:"errors,omitempty"`
	Success *bool `json:"success,omitempty"`
	Data *WorkspaceCreateResponseAllOfData `json:"data,omitempty"`
}

// NewWorkspaceCreateResponse instantiates a new WorkspaceCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceCreateResponse() *WorkspaceCreateResponse {
	this := WorkspaceCreateResponse{}
	return &this
}

// NewWorkspaceCreateResponseWithDefaults instantiates a new WorkspaceCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceCreateResponseWithDefaults() *WorkspaceCreateResponse {
	this := WorkspaceCreateResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *WorkspaceCreateResponse) GetErrors() []Error13 {
	if o == nil || IsNil(o.Errors) {
		var ret []Error13
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceCreateResponse) GetErrorsOk() ([]Error13, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *WorkspaceCreateResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error13 and assigns it to the Errors field.
func (o *WorkspaceCreateResponse) SetErrors(v []Error13) {
	o.Errors = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *WorkspaceCreateResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceCreateResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *WorkspaceCreateResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *WorkspaceCreateResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *WorkspaceCreateResponse) GetData() WorkspaceCreateResponseAllOfData {
	if o == nil || IsNil(o.Data) {
		var ret WorkspaceCreateResponseAllOfData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceCreateResponse) GetDataOk() (*WorkspaceCreateResponseAllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *WorkspaceCreateResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given WorkspaceCreateResponseAllOfData and assigns it to the Data field.
func (o *WorkspaceCreateResponse) SetData(v WorkspaceCreateResponseAllOfData) {
	o.Data = &v
}

func (o WorkspaceCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableWorkspaceCreateResponse struct {
	value *WorkspaceCreateResponse
	isSet bool
}

func (v NullableWorkspaceCreateResponse) Get() *WorkspaceCreateResponse {
	return v.value
}

func (v *NullableWorkspaceCreateResponse) Set(val *WorkspaceCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceCreateResponse(val *WorkspaceCreateResponse) *NullableWorkspaceCreateResponse {
	return &NullableWorkspaceCreateResponse{value: val, isSet: true}
}

func (v NullableWorkspaceCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


