/*
CodeSandbox API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2023-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package csdkgo

import (
	"encoding/json"
)

// checks if the VMStartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VMStartResponse{}

// VMStartResponse struct for VMStartResponse
type VMStartResponse struct {
	Errors []Error10 `json:"errors,omitempty"`
	Success *bool `json:"success,omitempty"`
	Data *VMStartResponseAllOfData `json:"data,omitempty"`
}

// NewVMStartResponse instantiates a new VMStartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVMStartResponse() *VMStartResponse {
	this := VMStartResponse{}
	return &this
}

// NewVMStartResponseWithDefaults instantiates a new VMStartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVMStartResponseWithDefaults() *VMStartResponse {
	this := VMStartResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *VMStartResponse) GetErrors() []Error10 {
	if o == nil || IsNil(o.Errors) {
		var ret []Error10
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMStartResponse) GetErrorsOk() ([]Error10, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *VMStartResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error10 and assigns it to the Errors field.
func (o *VMStartResponse) SetErrors(v []Error10) {
	o.Errors = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *VMStartResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMStartResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *VMStartResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *VMStartResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *VMStartResponse) GetData() VMStartResponseAllOfData {
	if o == nil || IsNil(o.Data) {
		var ret VMStartResponseAllOfData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMStartResponse) GetDataOk() (*VMStartResponseAllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *VMStartResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given VMStartResponseAllOfData and assigns it to the Data field.
func (o *VMStartResponse) SetData(v VMStartResponseAllOfData) {
	o.Data = &v
}

func (o VMStartResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VMStartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableVMStartResponse struct {
	value *VMStartResponse
	isSet bool
}

func (v NullableVMStartResponse) Get() *VMStartResponse {
	return v.value
}

func (v *NullableVMStartResponse) Set(val *VMStartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVMStartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVMStartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVMStartResponse(val *VMStartResponse) *NullableVMStartResponse {
	return &NullableVMStartResponse{value: val, isSet: true}
}

func (v NullableVMStartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVMStartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


